### PR TITLE
Added option to exclude file patterns.

### PR DESCRIPTION
**Pull request by fuzzac**
e.g. cindex -exclude ".git *.obj *.deps" some/path

The pattern format is specified here: http://golang.org/pkg/path/filepath/#Match

### CODE REVIEW

**Comment by junkblocker** [comment]
Thanks for the pull request, @fuzzac . I've been wanting to implement git/mercurial style include/excludes accepted from a file but haven't gotten around to it. Specially, http://www.selenic.com/mercurial/hgignore.5.html is really convenient. I have slight reservation about having a command line option that we split as it will tend to run long.

In addition, the proposed syntax, or rather space character based splitting won't let us exclude files with spaces in them as it ignores the escape facility of the Match function.

Your current proposal only need a slight modification to achieve all the power of `filepath/Match()` supported patterns reading those from a file. 

Alternatively, this could be added as is and file based excludes can be added as an `-exclude-from` option like rsync though it will still retain the limitation unless we use `-exclude pat1 -exclude pat2 ...` style multi-valued options. The latter is the most appealing direction to me at this time for this.

Also, I'm wondering if we want to keep `.csearchindex` as the only hardcoded exclude if nothing is specified.

Let me mull this over while inviting your thoughts on this.

**Comment by fuzzac** [comment]
Thanks for the feedback.

Reading the patterns from a file works for me, assuming we're just talking
a list of glob patterns. More involved syntax with includes / excludes and
regexp / glob patterns would be useful too, but maybe that can wait?

I also like the idea of removing all the hard coded defaults except for
".csearchindex".

**Comment by junkblocker** [comment]
Yes, I think a list of globs is sufficient for now.

I do have a use case for includes which I've kind of wrapper scripted away for now (not published here). But I'll open another bug to track that separately.

BTW, we can have another file called `.csearchignore` to hold the default excludes next to default index file location which will of course always be in the default excludes. However, we don't need to rush into that for this change.

**Comment by junkblocker** [comment]
Merged. Cheers @fuzzac!

**Pull request merged**
